<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="Admin_ManageUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FeaturedContent" Runat="Server">
    <asp:HyperLink ID="refHome" runat="server" NavigateUrl="~/Admin/AdminUser.aspx">Home</asp:HyperLink>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" Runat="Server">
    <br />
    <asp:GridView ID="grdUserAccounts" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="dsManageUsers" OnRowEditing="grdUserAccounts_RowEditing" OnRowUpdated="grdUserAccounts_RowUpdated" OnSelectedIndexChanged="grdUserAccounts_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="userName" HeaderText="User Name" SortExpression="userName" />
            <asp:BoundField DataField="email" HeaderText="EMail" SortExpression="email" />
            <asp:BoundField DataField="lastLoginDate" HeaderText="Last Login" SortExpression="lastLoginDate" />
            <asp:BoundField DataField="roleName" HeaderText="Role" SortExpression="roleName" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="dsManageUsers" runat="server" ConnectionString="<%$ ConnectionStrings:aspnet-GA-20130209202047ConnectionString %>" SelectCommand="select u.userName,m.email,m.lastLoginDate,r.roleName from usersInRoles ur
join roles r on r.roleId = ur.roleId
join Users u on u.userid = ur.userId
join Memberships m on m.userId = ur.userId
where u.UserName != 'sadmin'"></asp:SqlDataSource>
    <br />
    <asp:HyperLink ID="refCreateUser" runat="server" Font-Size="Medium" ForeColor="Blue" NavigateUrl="~/Admin/CreateUser.aspx">Create a new User</asp:HyperLink>
</asp:Content>

